(() => {
  const API = window.SIMULATOR_API || 'http://127.0.0.1:8091';
  const GATEWAY_API = 'http://127.0.0.1:8093';
  const SCENARIOS = [['normal', '正常波动'], ['high-temperature', '高温告警'], ['low-pressure', '低压告警'], ['high-vibration', '振动异常']];
  const state = { devices: [], editing: null, log: JSON.parse(localStorage.getItem('simlab-log') || '[]'), gatewayDevices: [], scenario: null };
  const $ = id => document.getElementById(id);
  const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const statusText = status => ({ONLINE:'运行中', OFFLINE:'已停用', RECONNECTING:'重连中'})[status] || '未知';
  const statusClass = status => status === 'ONLINE' ? 'online' : status === 'RECONNECTING' ? 'reconnecting' : 'offline';
  const pointCount = device => Object.keys(device.points || {}).length;
  async function request(path, options) { const response = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(options?.headers || {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || `HTTP ${response.status}`); return body; }
  function toast(message) { const el = $('toast'); el.textContent = message; el.classList.remove('hidden'); window.clearTimeout(toast.timer); toast.timer = window.setTimeout(() => el.classList.add('hidden'), 2400); }
  function addLog(message) { state.log.unshift({ message, time: new Date().toLocaleTimeString('zh-CN') }); state.log = state.log.slice(0, 12); localStorage.setItem('simlab-log', JSON.stringify(state.log)); renderLog(); }
  function renderLog() { $('activityLog').innerHTML = state.log.length ? state.log.map(item => `<div class="log-entry"><span>${escapeHtml(item.message)}</span><time>${escapeHtml(item.time)}</time></div>`).join('') : '<p class="log-empty">暂无操作记录</p>'; }
  function renderStats() { const total = state.devices.length; const online = state.devices.filter(d => d.status === 'ONLINE').length; const attention = state.devices.filter(d => d.status !== 'ONLINE').length; const rate = state.devices.filter(d => d.status === 'ONLINE' && d.enabled).reduce((sum, d) => sum + Object.keys(d.points || {}).length / Math.max(.2, d.intervalSec || 1), 0); $('totalCount').textContent = total; $('onlineCount').textContent = online; $('attentionCount').textContent = attention; $('rateCount').innerHTML = `${rate >= 10 ? Math.round(rate) : rate.toFixed(1)}<span> msg/s</span>`; $('rateCount').closest('.stat-card').title = '按各在线设备的测点数与采集周期推算的理论速率'; }
  function renderDevices() { const search = $('searchInput').value.trim().toLowerCase(); const filter = $('statusFilter').value; const list = state.devices.filter(d => (!search || `${d.deviceCode} ${d.name}`.toLowerCase().includes(search)) && (filter === 'ALL' || d.status === filter)); $('emptyState').classList.toggle('hidden', list.length > 0); $('deviceGrid').innerHTML = list.map(device => { const points = Object.entries(device.points || {}); return `<article class="device-card"><div class="device-head"><div class="device-title"><strong>${escapeHtml(device.deviceCode)}</strong><small>${escapeHtml(device.name)} · ${escapeHtml(device.deviceType)}</small></div><span class="status-pill ${statusClass(device.status)}">${statusText(device.status)}</span></div><div class="device-meta"><span>运行场景<b>${escapeHtml(device.scenario)}</b></span><span>采集周期<b>${device.intervalSec}s</b></span><span>业务心跳<b>${device.heartbeatIntervalSec}s</b></span></div><div class="point-chips">${points.length ? points.map(([code, point]) => `<span class="point-chip">${escapeHtml(code)} ${escapeHtml(point.base)}${escapeHtml(point.unit)}</span>`).join('') : '<small>暂无测点</small>'}</div><div class="device-footer"><small>${device.lastData ? `最近数据 ${new Date(device.lastData).toLocaleTimeString('zh-CN')}` : '等待数据'}</small><div class="device-actions"><button class="small-outline" data-action="edit" data-code="${escapeHtml(device.deviceCode)}">编辑</button><button class="small-outline" data-action="toggle" data-code="${escapeHtml(device.deviceCode)}">${device.enabled ? '停用' : '启动'}</button><button class="small-danger" data-action="delete" data-code="${escapeHtml(device.deviceCode)}">删除</button></div></div></article>`; }).join(''); renderStats(); }
  function pointRow(code, point) { return `<div class="point-row" data-point="${escapeHtml(code)}"><b>${escapeHtml(code)}</b><input data-field="base" type="number" step="0.01" value="${escapeHtml(point.base ?? 0)}"><input data-field="variation" type="number" min="0" step="0.01" value="${escapeHtml(point.variation ?? 1)}"><input data-field="unit" value="${escapeHtml(point.unit || '')}" placeholder="单位"><button type="button" class="remove-point" title="删除测点">×</button></div>`; }
  function openModal(device) { state.editing = device ? device.deviceCode : null; $('modalTitle').textContent = device ? '编辑虚拟设备' : '添加虚拟设备'; $('deviceCode').value = device?.deviceCode || `SIM-${String(state.devices.length + 1).padStart(3, '0')}`; $('deviceCode').disabled = !!device; $('deviceName').value = device?.name || '新模拟设备'; $('deviceType').value = device?.deviceType || 'PLC'; $('scenario').value = device?.scenario || 'normal'; $('intervalSec').value = device?.intervalSec || 1; $('heartbeatSec').value = device?.heartbeatIntervalSec || 10; $('enabled').checked = device ? device.enabled : true; const points = device?.points || { temperature: { base: 65, variation: 3, unit: 'C' } }; $('pointRows').innerHTML = Object.entries(points).map(([code, point]) => pointRow(code, point)).join(''); $('modal').classList.remove('hidden'); $('deviceName').focus(); }
  function closeModal() { $('modal').classList.add('hidden'); state.editing = null; }
  function collectPoints() { const points = {}; document.querySelectorAll('.point-row').forEach(row => { const code = row.dataset.point; points[code] = {}; row.querySelectorAll('[data-field]').forEach(input => { points[code][input.dataset.field] = input.dataset.field === 'unit' ? input.value : Number(input.value); }); }); return points; }
  async function saveDevice(event) { event.preventDefault(); const points = collectPoints(); if (!Object.keys(points).length) return toast('至少添加一个测点'); const payload = { deviceCode: $('deviceCode').value.trim().toUpperCase(), name: $('deviceName').value.trim(), deviceType: $('deviceType').value, scenario: $('scenario').value, enabled: $('enabled').checked, intervalSec: Number($('intervalSec').value), heartbeatIntervalSec: Number($('heartbeatSec').value), points }; $('saveBtn').disabled = true; try { if (state.editing) { await request(`/api/devices/${encodeURIComponent(state.editing)}`, { method: 'PUT', body: JSON.stringify(payload) }); addLog(`修改 ${payload.deviceCode}`); toast('设备配置已更新'); } else { await request('/api/devices', { method: 'POST', body: JSON.stringify(payload) }); addLog(`新增 ${payload.deviceCode}`); toast('设备已添加'); } closeModal(); await load(); } catch (error) { toast(error.message); } finally { $('saveBtn').disabled = false; } }
  async function operate(code, action) { try { if (action === 'delete' && !window.confirm(`确定删除 ${code} 吗？`)) return; const label = action === 'delete' ? '删除' : action === 'toggle' ? '切换状态' : action; await request(`/api/devices/${encodeURIComponent(code)}${action === 'toggle' ? '/toggle' : ''}`, { method: action === 'delete' ? 'DELETE' : 'POST' }); addLog(`${label} ${code}`); toast(`${label}成功`); await load(); } catch (error) { toast(error.message); } }
  async function load() { try { const health = await request('/health'); $('serviceStatus').textContent = health.status === 'UP' ? '在线' : '异常'; state.devices = await request('/api/devices'); renderDevices(); updateGatewayNote(); $('syncLabel').textContent = `最后同步 ${new Date().toLocaleTimeString('zh-CN')}`; } catch (error) { $('serviceStatus').textContent = '未连接'; $('deviceGrid').innerHTML = ''; toast('控制服务未启动，请运行 start-all.ps1'); } }
  async function loadGateway() {
    try {
      const health = await window.fetch(`${GATEWAY_API}/health`).then(r => r.json());
      state.gatewayDevices = health.devices || [];
      try { state.scenario = (await window.fetch(`${GATEWAY_API}/api/scenario`).then(r => r.json())).scenario; } catch { state.scenario = null; }
      $('modbusEmpty').classList.add('hidden');
    } catch {
      state.gatewayDevices = []; state.scenario = null;
      $('modbusEmpty').classList.remove('hidden');
    }
    renderGateway();
  }
  function updateGatewayNote() { $('gatewayNote').textContent = `工业监控台设备总数 ${state.devices.length + state.gatewayDevices.length} = 模拟器 ${state.devices.length} + Modbus ${state.gatewayDevices.length}`; }
  function renderGateway() {
    const grid = $('modbusGrid');
    grid.innerHTML = state.gatewayDevices.map(code => {
      const buttons = SCENARIOS.map(([value, label]) =>
        `<button class="small-outline${state.scenario === value ? ' scenario-active' : ''}" data-scenario="${value}"${state.scenario === null ? ' disabled' : ''}>${label}</button>`).join('');
      return `<article class="device-card"><div class="device-head"><div class="device-title"><strong>${escapeHtml(code)}</strong><small>Modbus TCP · 点位表采集</small></div><span class="status-pill online">网关接入</span></div><div class="device-meta"><span>当前场景<b>${escapeHtml(state.scenario ?? '未知')}</b></span><span>切换方式<b>写寄存器 HR15</b></span></div><div class="scenario-actions">${buttons}</div></article>`;
    }).join('');
    updateGatewayNote();
  }
  async function switchScenario(scenario) {
    try {
      await window.fetch(`${GATEWAY_API}/api/scenario`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ scenario }) });
      addLog(`Modbus 场景切换 → ${scenario}`);
      toast(`场景已切换：${scenario}`);
      await loadGateway();
    } catch { toast('场景切换失败：网关未启动'); }
  }
  $('addBtn').addEventListener('click', () => openModal()); $('refreshBtn').addEventListener('click', load); $('closeModal').addEventListener('click', closeModal); $('cancelBtn').addEventListener('click', closeModal); $('deviceForm').addEventListener('submit', saveDevice); $('searchInput').addEventListener('input', renderDevices); $('statusFilter').addEventListener('change', renderDevices); $('clearLogBtn').addEventListener('click', () => { state.log = []; localStorage.removeItem('simlab-log'); renderLog(); }); $('deviceGrid').addEventListener('click', event => { const button = event.target.closest('button[data-action]'); if (!button) return; const device = state.devices.find(item => item.deviceCode === button.dataset.code); if (button.dataset.action === 'edit') openModal(device); else operate(button.dataset.code, button.dataset.action); }); $('addPointBtn').addEventListener('click', () => { const input = $('newPoint'); const code = input.value.trim().toLowerCase(); if (!code || document.querySelector(`[data-point="${CSS.escape(code)}"]`)) return; $('pointRows').insertAdjacentHTML('beforeend', pointRow(code, { base: 0, variation: 1, unit: '' })); input.value = ''; }); $('pointRows').addEventListener('click', event => { if (event.target.closest('.remove-point')) event.target.closest('.point-row').remove(); }); $('modal').addEventListener('click', event => { if (event.target === $('modal')) closeModal(); }); $('modbusGrid').addEventListener('click', event => { const button = event.target.closest('button[data-scenario]'); if (button) switchScenario(button.dataset.scenario); }); renderLog(); load(); loadGateway(); window.setInterval(load, 3000); window.setInterval(loadGateway, 5000);
})();
